### ISSUE TITLE
Small issue - suggestion - lightning sensor

### ISSUE THREAD

**Issue by Notrial** [briis/smartweather#60] opened 2021-02-18 10:23 UTC
Any chance we can display sensor.smartweather_lightning_time in a more "human" way? 
As in "5 days ago", or "20 mins ago" instead of a timestamp.

Thanks!

**Comment by briis** [comment] 2021-02-18 13:53
Yes it could be done. But I am not sure I will do it here. For you English might be great, but for others they would like it in their local language. With javascript, I would just use moment.js, as this can do this very easy, but this is done in Python, and I don't know a Library like moment.js with multi language support.

I have not testet this, but couldn't you create a template sensor that converts this?

**Comment by Notrial** [comment] 2021-02-18 15:06
I get your point and yeah sure, should be doable as a new template sensor :) 
What I don't get is why this timestamp isn't displayed as "since" as for example my Shelly switch sensors are...

This is how it looks:
![image](https://user-images.githubusercontent.com/36201754/108368623-f4ef0580-71fa-11eb-8d14-5a9d45afa98a.png)

And this is when its added to lovelace:
![image](https://user-images.githubusercontent.com/36201754/108368679-0506e500-71fb-11eb-865d-202326c151ab.png)

This Weatherflow one is:
![image](https://user-images.githubusercontent.com/36201754/108368728-13ed9780-71fb-11eb-9ccd-a2cf738d54cf.png)

and looks the same when added as entity...

![Uploading image.png…]()

**Comment by briis** [comment] 2021-02-18 15:43
That is most likely caused by the fact that I format the date differently. I believe when you have the T in the time filed it is formatted as an ISO time, and that get picked up differently by HA. I can have a look at that.

**Comment by Notrial** [comment] 2021-02-18 15:45
Awesome!

**Comment by briis** [comment] 2021-03-07 10:44
I have now released V2.2.3, which fixes your issue. The simple fix was actually to set the sensors device_class to `timestamp`, because when you do that it will act differently on Lovelace Cards. But I also changed to a valid date time variable, so that we ensure it can be properly converted in Lovelace.

If you are satisfied with the solution, please close the issue.

**Comment by Notrial** [comment] 2021-03-08 09:57
Works like a charm!

**Comment by briis** [comment] 2021-03-18 07:39
I will close this now, as this is fixed.

**Closed by briis** 2021-03-18 07:39 UTC
Labels: feature-request
