### ISSUE TITLE
Integration suddenly stopped working

### ISSUE THREAD

**Issue by jayscovill** [briis/smartweather#61] opened 2021-02-28 14:47 UTC
Last night after a restart of HASS the integration suddenly stopped working and all the entities show as unavailable.  I've tried restarting Home Assistant several times as well as reloading the but it hasn't fixed it.  I also tried deleteing and re-adding the integration but now no entities are populated at all in the integration.

Anyone else running into this?

**Comment by briis** [comment] 2021-02-28 15:18
Har station id are you using? Then I can check out if there is anything wrong with the station

**Comment by jayscovill** [comment] 2021-02-28 15:26
42239. The Tempest App is reading data ok.

Thanks!

**Comment by briis** [comment] 2021-02-28 15:37
it looks strange on the API Test Page. Try an key in your station ID and Token on this page, as this is the same data the Integration gets, and when I do it, using the old developer key, I don't get any data.


https://weatherflow.github.io/Tempest/api/swagger/#!/observations/getStationObservation

Start by clicking the Authorize button, and enter the token you are using in the Integration. Then expand the section"Get Observations" and key in your station ID in the "Get the latest Station observation". This should display some data, but when I do it, I only get "SUCCESS - Either no capabilities or no recent observations"

Are you owning the the station? If yes, have you generated your own Token?

**Comment by jayscovill** [comment] 2021-02-28 15:45
Yes, my station and token has been generated. I even created a new API key in case something happened to the old one.

I have a ticket in with Weatherflow.  We'll see what they say.

**Comment by briis** [comment] 2021-02-28 15:52
Did you get the same result on the API site with your personal token?
Is your bridge running? Maybe try and unplug the bridge, and wait for 10 seconds and then plug it in again. That sometimes helps - You might get data on the tempest app, as the APP tries to connect using bluetooth to the bridge, but the bridge might be disconnected from the internet, so it cannot send data out.

**Comment by jayscovill** [comment] 2021-02-28 15:59
Yes, same result.  Bridge is running and the information on the Tempest website is up to date.  And showing my station online.  I cycled power for good measure but no change.  Wondering if something has happened to my API authorization.

**Comment by briis** [comment] 2021-02-28 16:12
Really strange - once you see data on the above site, you should also have them in the Integration. Just tested with my own station and the developer token and my personal token - both deliver the data. Let me know what Weatherflow says.

**Comment by jayscovill** [comment] 2021-02-28 20:26
Bah! My Tempest was offline.  I finally dug down deep enough into the settings to find out out...I got it reconnected by hitting the reset button for 10 seconds...but if I have to keep doing that every week I'm going to be annoyed as it's on a 10 ft poll lol

Thanks for your help.

**Comment by briis** [comment] 2021-03-01 06:58
Glad you found the cause, but yes, let us hope this is only a one-time experience. I will close the issue now.

**Closed by briis** 2021-03-01 06:58 UTC
